### ISSUE TITLE
Name change suggestion

### ISSUE THREAD

**Issue by ottomata** [Pchelolo/librdkafka-node#2]
node-rdkafka

?

**Comment by Pchelolo** [comment]
@ottomata hehe :) Let the bikeshed begin!

I agree that we need a new name, `node-rdkafka` looks ok to me. @Gwicke @d00rman @EEvans what do you think?

**Comment by d00rman** [comment]
I guess we can go with the usual ports-to-node conventions and have `node-rdkafka` as the official name of this gem :+1:

**Comment by Pchelolo** [comment]
Done.
